version: '3'                                                                    
services:                                                                       
  app:
    build: ./
    ports: 
      - "8000:8000"
    expose: 
      - 8000
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: credentials.json
    volumes:
      - .:/opt/project
  
  db:                                                                         
    image: mysql:5.7
    environment:                                                            
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transcriber
    expose:                                                                 
      - 3306                                                              
    ports:                                                                  
      - 3306:3306