version: '3'                                                                    
services:                                                                       
  app:
    build: ./
    ports: 
      - "8000:8000"
    expose: 
      - 8000
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: credentials.json
    volumes:
      - .:/opt/project