# Generated by Django 3.1.7 on 2021-03-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0006_auto_20210306_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_ext',
            name='session',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
