# Generated by Django 3.1.7 on 2021-03-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0007_auto_20210306_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='hashed',
            field=models.CharField(default='dfsdf', max_length=50),
            preserve_default=False,
        ),
    ]
